<a href="https://colab.research.google.com/github/kimchaeyoung-student/pdm04/blob/master/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [1]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array
data = asarray(data)

# summarize the array content
print(data)

# summarize the array shape
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [2]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array
data = asarray(data)
print(data)

# step through rows
for row in range(data.shape[0]):
	print(data[row, :])
 

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


## Print columns

In [3]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array
data = asarray(data)
print(data)

# step through columns
for col in range(data.shape[1]):
	print(data[ : ,col])

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [5]:
# sum values array-wise
from numpy import asarray

# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array (리스트를 배열로 만든다)
data = asarray(data)

# summarize the array content
print(data)

# sum data by array
result = data.sum(axis=None)

# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [6]:
# sum values column-wise
from numpy import asarray

# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array
data = asarray(data)

# summarize the array content
print(data)

# sum data by column
result = data.sum(axis=0)

# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [7]:
# sum values row-wise
from numpy import asarray

# define data as a list
data = [[1,2,3], [4,5,6]]

# convert to a numpy array
data = asarray(data)

# summarize the array content
print(data)

# sum data by row
result = data.sum(axis=1)

# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[ 6 15]


## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [도전하기]

- 3차원 배열을 리스트로부터 만드시오.

In [ ]:
# Make 3d-array in numpy
'''
data = [[1,2,3], [4,5,6]]
'''

In [10]:
data3d = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
from numpy import asarray
data3d = asarray(data3d)

In [12]:
data3d.ndim # 3차원 배열이 아님

2

### 3차원 배열 : n x m x l , (n,m,l)

In [13]:
data3d = [[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]] # 2차원 배열이 3개 있는 형태
data3d = asarray(data3d)
data3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
data3d.ndim

3

In [15]:
data3d.shape

(3, 2, 3)

In [22]:
data3d

# 바깥쪽 괄호 [] 부터 시작하여 괄호를 기준으로 차원이 3, 2, 3 이 된다. 즉,
# 가장 바깥쪽 괄호 안에는 3개의 원소가 존재한다.
# 두번째 괄호 안에는 2개의 원소가 존재한다.
# 세번째 괄호 안에는 3개의 원소가 존재한다.

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
data3d.sum(axis=None)

# 3차원 배열의 모든 원소를 더한 값을 출력한다. 결과는 1개의 스칼라값

63

In [24]:
data3d.sum(axis=0)

# axis=0이면 첫번째 괄호가 사라졌을 때, 남은 2차원 원소들이 하나로 더해진다.

# 2차원 배열의 대응하는 원소끼리 더하면 된다. 결과는 (2x3)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [25]:
data3d.sum(axis=1)

# axis=1이면 두번째 괄호가 사라졌을 때, 남은 1차원 원소들이 각각 하나로 더해진다. 결과는 (3x3)

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [26]:
data3d.sum(axis=2)

# axis=2이면 세번째 괄호가 사라졌을 때, 남은 스칼라 원소들이 각각 하나로 더해진다. 결과는 (3x2)

array([[ 6, 15],
       [ 6, 15],
       [ 6, 15]])

In [27]:
data3d.sum(axis=(0,1))

# axis=(0,1)이면 첫번째, 두번째 괄호가 사라지면서 남는 1차원 배열의 각각 대응하는 원소끼리 더해진다.

array([15, 21, 27])

In [28]:
data3d.sum(axis=(0,2))

# axis=(0,2)이면 첫번째, 세번째 괄호가 사라지면서 남는 2차원 배열의 각각 대응하는 원소끼리 더해진다.

array([18, 45])

In [29]:
data3d.sum(axis=(1,2))

# axis=(1,2)이면 두번째, 세번째 괄호가 사라지면서 남는 스칼라가 모두 더해진다.

array([21, 21, 21])

### 위의 3차원 배열에 대한 계산 결과를 간단히 주석으로 설명해보세요.